version: '3'

services:
  app:
    working_dir: /app
    container_name: app
    volumes:
      - .:/app
    build: .
    command: bash -c "php receive.php"

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq